name: Build release
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        working-directory: .build
        run: |
          apt-get update
          apt-get install -y make
          make install
      - name: Build release
        working-directory: .build
        run: make -j
      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          name: Latest build
          tag_name: continuous
          overwrite_files: true
          fail_on_unmatched_files: true
          working_directory: .build
          body: |
            Requires internet during the initial setup
          files: |
            windows/Web-NXDT.exe
            macos/Web-NXDT.app.zip
            linux/Web-NXDT.AppImage